version: 0.1

phases:
  build:
    commands:
      - echo nothing to do yet
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main
    - images/*
